import * as Yup from "yup";

export const initialValues = {
  input01: "",
  input02: "",
  input03: "",
  input04: "",
  input05: "",
  input06: "",
  input07: "",
  input08: "",
  input09: "",
  input10: "",
  input11: "",
  input12: "",
  input13: "",
  input14: "",
  input15: "",
  input16: "",
  input17: "",
  input18: "",
  input19: "",
  input20: "",
};

export const validationSchema = Yup.object().shape({
  input01: Yup.string().notRequired(),
  input02: Yup.string().notRequired(),
  input03: Yup.string().notRequired(),
  input04: Yup.string().notRequired(),
  input05: Yup.string().notRequired(),
  input06: Yup.string().notRequired(),
  input07: Yup.string().notRequired(),
  input08: Yup.string().notRequired(),
  input09: Yup.string().notRequired(),
  input10: Yup.string().notRequired(),
  input11: Yup.string().notRequired(),
  input12: Yup.string().notRequired(),
  input13: Yup.string().notRequired(),
  input14: Yup.string().notRequired(),
  input15: Yup.string().notRequired(),
  input16: Yup.string().notRequired(),
  input17: Yup.string().notRequired(),
  input18: Yup.string().notRequired(),
  input19: Yup.string().notRequired(),
  input20: Yup.string().notRequired(),
});
